# Generated by Django 5.0.3 on 2024-11-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantattributemapping',
            name='is_valid',
        ),
    ]
