# Generated by Django 5.0.3 on 2024-10-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
    ]
