# Generated by Django 5.0.3 on 2024-11-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241015_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='link_hash',
        ),
        migrations.CreateModel(
            name='LinkMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_links', to='products.productvariant')),
            ],
        ),
    ]
