# urls.py
from django.urls import path
from .views import (UserRegistrationView,
RequestOTPView,
VerifyOTPView,
UserDetailView,
RoleMasterDetailView,
RoleMasterListView,
StateListCreateView,
CityListCreateView,
StoreSignatureGSTView,
StoreBankDetailsView,
StoreCreateView,
StoreCancelView,
UserRegistrationViewBusiness,
)
urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('business-register/', UserRegistrationViewBusiness.as_view(), name='business-register'),
    # path('login/', UserLoginView.as_view(), name='login'),
    path('login/request-otp/', RequestOTPView.as_view(), name='request-otp'),
    path('login/verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('users/', UserDetailView.as_view(), name='user-list'),
    path('roles/', RoleMasterListView.as_view(), name='role-list'),
    path('roles/<int:pk>/', RoleMasterDetailView.as_view(), name='role-detail'),
    path('states/', StateListCreateView.as_view(), name='state-list'),
    path('cities/', CityListCreateView.as_view(), name='city-list'),
    path('store/gst-signature/', StoreSignatureGSTView.as_view(), name='store-signature-gst'),
    path('store-bank-details/', StoreBankDetailsView.as_view(), name='store-bank-details'),
    path('create-store/', StoreCreateView.as_view(), name='create-store'),
    path('cancel-registration/<int:pk>/', StoreCancelView.as_view(), name='cancel-registration'),   
]
