# Generated by Django 5.0.3 on 2024-09-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_date_user_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile_no',
        ),
    ]
