# Generated by Django 5.0.3 on 2024-10-03 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_otp_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100, null=True)),
                ('store_email', models.EmailField(max_length=100, null=True)),
                ('store_phone', models.CharField(max_length=10, null=True)),
                ('business_type', models.CharField(max_length=200, null=True)),
                ('signature_hash', models.CharField(max_length=255, null=True)),
                ('address_line_1', models.CharField(max_length=150, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.BigIntegerField(null=True)),
                ('bank_account_holder_name', models.CharField(max_length=100, null=True)),
                ('bank_ifsc_code', models.CharField(max_length=20, null=True)),
                ('bank_account_type', models.CharField(max_length=50, null=True)),
                ('is_gst', models.CharField(choices=[('I Have GSTIN Number', 'I Have GSTIN Number'), ('I Want To Sell Products That Exempt GSTIN', 'I Want To Sell Products That Exempt GSTIN'), ("I Don't Have GSTIN Number OR I Have Applied For GSTIN", "I Don't Have GSTIN Number OR I Have Applied For GSTIN")], max_length=100, null=True)),
                ('pan_no', models.CharField(max_length=20, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.citymaster')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.statemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
