# Generated by Django 5.0.3 on 2024-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_storemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemaster',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
