# Generated by Django 5.0.3 on 2024-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_storemaster_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemaster',
            name='bill_image_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storemaster',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
