# Generated by Django 5.0.3 on 2024-10-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_storemaster_bill_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemaster',
            name='store_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
