# Generated by Django 5.0.3 on 2024-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_storemaster_store_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemaster',
            name='cheque_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
